# Generated by Django 4.0.5 on 2022-06-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sstudent_det', '0002_student_sub1_student_sub2_student_sub3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
